version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: pip
    registries: "*"
    directory: "/"
    insecure-external-code-execution: allow
    versioning-strategy: increase-if-necessary
    schedule:
      interval: "daily"
    groups:
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"
      public-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
