[tool.poetry]
name = "compiler-config"
version = "0.1.1"
description = ""
authors = ["jamie <jfriel@oxfordquantumcircuits.com>"]
readme = "README.md"

packages = [
    { include = "compiler_config" }
]


[tool.poetry.dependencies]
python = ">=3.9,<3.13"


[tool.poetry.group.dev.dependencies]
pytest = "~8.4.1"
ruff = "^0.12.8"
pip-audit = "^2.9.0"
pre-commit = "^3.2.0"


[tool.ruff]
line-length = 92

[tool.ruff.lint]
extend-select = ["I"]

[tool.ruff.lint.per-file-ignores]
# Ignore a == b comparisons for tests
"tests/**" = ["E721"]

[tool.ruff.lint.isort]
known-first-party = ["compiler_config"]
known-local-folder = ["tests"]


[tool.poetry.scripts]
format-code = "poetry_scripts:format_code"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
