name: Publish package to PyPI and TestPyPI

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version of the project eg 1.2.3'
        type: string
        required: true

env:
  PYTHON_VERSION: "3.10"

jobs:
  final-tests: 
    name: Final tests
    uses: ./.github/workflows/package-tests.yml

  build:
    name: Build package
    runs-on: ubuntu-24.04
    needs: final-tests
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:

      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install Poetry and Dynamic Versioning plugin
        run: |
          pipx install poetry
          pipx inject poetry "poetry-dynamic-versioning[plugin]"

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install packaging
        run: |
          pip install packaging

      - name: Get current version
        id: current
        run: |
          echo "version=$(poetry version -s)" >> "$GITHUB_OUTPUT"

      - name: Validate version
        id: validate-tag
        env:
          NEW_VERSION: ${{ inputs.version }}
          CURRENT_VERSION: ${{ steps.current.outputs.version }}
        shell: python
        run: |
          from packaging.version import Version, InvalidVersion
          import sys
          import os

          new_version = os.getenv("NEW_VERSION")
          current_version = os.getenv("CURRENT_VERSION")

          try:
              Version(new_version)
          except InvalidVersion:
              print(f"Error: '{new_version}' is not a valid version.")
              sys.exit(1)

          if Version(new_version) <= Version(current_version):
              print(f"Error: New version '{new_version}' must be greater than current version '{current_version}'.")
              sys.exit(1)

      - name: Generate tag
        id: tag
        shell: bash
        env:
          VERSION: ${{ inputs.version }}
        run: |
          git tag "$VERSION"
          echo "tag=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Poetry build
        run: poetry build

      - name: Store the distribution packages
        uses: actions/upload-artifact@v7
        with:
          name: python-package-distributions
          path: dist/

  publish-to-testpypi:
    name: Publish to TestPyPI
    runs-on: ubuntu-24.04
    environment: test-pypi
    permissions:
      id-token: write
    needs: build
    env:
      name: testpypi
      url: https://test.pypi.org/p/qat-config
    
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v8
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish distribution 📦 to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true
          skip-existing: true

  publish-to-pypi:
    name: Publish to PyPI
    needs:
    - build
    - publish-to-testpypi
    environment: pypi
    runs-on: ubuntu-24.04
    env:
      name: pypi
      url: https://pypi.org/p/qat-config  # Replace <package-name> with your PyPI project name
    permissions:
      id-token: write
      contents: write

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v8
      with:
        name: python-package-distributions
        path: dist/

    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        verbose: true
        skip-existing: true

    - name: Sign the dists with Sigstore
      uses: sigstore/gh-action-sigstore-python@v3.3.0
      with:
        inputs: >-
          ./dist/*.tar.gz
          ./dist/*.whl

    - name: Create GitHub Release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: >-
        gh release create
        '${{ needs.build.outputs.tag }}'
        --repo '${{ github.repository }}'
        --generate-notes
        --title "${{ needs.build.outputs.tag }}"
        --latest
        
    - name: Upload artifact signatures to GitHub Release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      # Upload to GitHub Release using the `gh` CLI.
      # `dist/` contains the built packages, and the
      # sigstore-produced signatures and certificates.
      run: >-
        gh release upload
        '${{ needs.build.outputs.tag }}' dist/**
        --repo '${{ github.repository }}'
