name: Publish package to PyPI and TestPyPI

on:
  workflow_dispatch:
    inputs:
      bump:
        description: "The type of version bump to apply"
        required: true
        default: "patch"
        type: choice
        options:
          - "patch"
          - "minor"
          - "major"

env:
  PYTHON_VERSION: "3.10"

jobs:
  final-tests: 
    name: Final tests
    uses: ./.github/workflows/package-tests.yml

  release:
    runs-on: ubuntu-22.04
    needs: final-tests
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'poetry'

      - name: Install dependencies
        run: poetry sync

      - name: Generate tag
        id: tag
        shell: bash
        run: |
          BUMP_TYPE=${{ inputs.bump }}
          LATEST_TAG=$(git tag --list --sort=-v:refname | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | head -n1)
          IFS='.' read -r MAJOR MINOR PATCH <<< "$LATEST_TAG"
          case "$BUMP_TYPE" in
            major)
              MAJOR=$((MAJOR + 1))
              MINOR=0
              PATCH=0
              ;;
            minor)
              MINOR=$((MINOR + 1))
              PATCH=0
              ;;
            patch)
              PATCH=$((PATCH + 1))
              ;;
          esac
          NEW_TAG="$MAJOR.$MINOR.$PATCH"
          echo "$NEW_TAG"
          echo "tag=$NEW_TAG" >> $GITHUB_OUTPUT

      - name: Check tag validity
        if: always()
        shell: bash
        run: |
          if [[ ! "${{ steps.tag.outputs.tag }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "❌ Tag is invalid. Aborting release."
            exit 1
          fi

      - name: Tag release
        run: |
          git tag ${{ steps.tag.outputs.tag }}

      - name: Check poetry version matches tag
        run: | 
          POETRY_VERSION=$(poetry version -s)
          [[ $POETRY_VERSION = ${{ steps.tag.outputs.tag }} ]] || {
            echo "❌ Poetry version does not match tag. Aborting release."
            exit 1
          }

      - name: Poetry build
        run: poetry build

      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  publish-to-testpypi:
    name: Publish to TestPyPI
    runs-on: ubuntu-22.04
    environment: test-pypi
    permissions:
      id-token: write
    needs: release
    env:
      name: testpypi
      url: https://test.pypi.org/p/qat-config
    
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v5
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish distribution 📦 to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true
          skip-existing: true

  publish-to-pypi:
    name: Publish to PyPI
    needs:
    - release
    - publish-to-testpypi
    environment: pypi
    runs-on: ubuntu-22.04
    env:
      name: pypi
      url: https://pypi.org/p/qat-config  # Replace <package-name> with your PyPI project name
    permissions:
      id-token: write
      contents: write

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v5
      with:
        name: python-package-distributions
        path: dist/

    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        verbose: true
        skip-existing: true

    - name: Sign the dists with Sigstore
      uses: sigstore/gh-action-sigstore-python@v3.1.0
      with:
        inputs: >-
          ./dist/*.tar.gz
          ./dist/*.whl

    - name: Create GitHub Release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: >-
        gh release create
        '${{ needs.release.outputs.tag }}'
        --repo '${{ github.repository }}'
        --generate-notes
        --title "${{ needs.release.outputs.tag }}"
        --latest
        
    - name: Upload artifact signatures to GitHub Release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      # Upload to GitHub Release using the `gh` CLI.
      # `dist/` contains the built packages, and the
      # sigstore-produced signatures and certificates.
      run: >-
        gh release upload
        '${{ needs.release.outputs.tag }}' dist/**
        --repo '${{ github.repository }}'
